game_sthar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls'))
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product_flutter, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, delete_data, increase_amount, decrease_amount, get_product_json, add_product_ajax, delete_product_ajax

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete/<int:id>', delete_data, name='delete_data'),
    path('increase_amount/', increase_amount, name='increase_amount'),
    path('decrease_amount/', decrease_amount, name='decrease_amount'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete-product-ajax/<int:id>', delete_product_ajax, name='delete_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),


]

main/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User


# Create your models here.
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    data_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField(max_length=400)
    price = models.IntegerField()
    category = models.TextField(max_length=255)
    platform = models.TextField(max_length=255)

main/forms.py
from django import forms
from main.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description","category", "platform", "amount" ,"price"]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md'}),
            'description': forms.TextInput(attrs={'class': 'border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md'}),
            'platform': forms.TextInput(attrs={'class': 'border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md'}),
            'category': forms.TextInput(attrs={'class': 'border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md'}),
            'amount': forms.NumberInput(attrs={'class': 'border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md'}),
            'price': forms.NumberInput(attrs={'class': 'border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md'}),
           
        }
    

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from main.forms import ProductForm
from main.signupforms import SignUpForm
from django.urls import reverse
from main.models import Product
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt
import datetime
import json


# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)
    jumlah_item = products.count()

    context = {
        'name': request.user.username, # Nama kamu
        'class': 'PBP A', # Kelas PBP kamu
        'jumlah_item' : jumlah_item,
        'products': products,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

@csrf_exempt
def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

@csrf_exempt
def add_product_ajax(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        category = request.POST.get("category")
        platform = request.POST.get("platform")
        amount = request.POST.get("amount")
        user = request.user

        new_product = Product(name=name, price=price, description=description, category=category, platform=platform, amount=amount, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)
    
    return HttpResponseNotFound()

@csrf_exempt
def delete_product_ajax(request,id):
    if request.method == "DELETE":
        item = Product.objects.get(pk = id)
        item.delete()

        return HttpResponse(b"DELETED", status=201)
    
    return HttpResponseNotFound()
        

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type = "application/json")

def show_xml_by_id(request,id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request,id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def register(request):
    form = SignUpForm()

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def delete_data(request, id):
    data = Product.objects.get(pk=id)
    data.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def increase_amount(request):
    if request.method == "POST":
        id_item= request.POST.get("id")
        data = Product.objects.get(pk=id_item)
        data.amount += 1
        data.save()
        return HttpResponse(b"POST", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def decrease_amount(request):
    if request.method == "POST":
        id_item = request.POST.get("id")
        data = Product.objects.get(pk=id_item)
        if (data.amount > 0):
            data.amount -= 1
        else:
            data.amount = 0
        data.save()
        return HttpResponse(b"POST", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"],
            amount = int(data["amount"]),
            platform = data["platform"],
            category = data["category"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}


<div class="min-h-screen bg-gray-100 text-gray-800 antialiased px-4 py-6 flex flex-col flex-wrap justify-center sm:py-12">
    <div class="relative py-2 sm:max-w-xl mx-auto text-center">
        <span class="text-2xl font-light">Add New Game</span>
        <div class="relative mt-4 bg-white shadow-md sm:rounded-lg text-left sm:mt-4">
            <div class="py-10 px-8">
                <form method="POST" action=""> 
                    {% csrf_token %}
                    {{form.as_p}}
                    <div class="flex justify-center">
                        <button class="mt-5 bg-green-500 text-white py-2 px-20 rounded-lg hover:bg-green-600 " type="submit" value="Add Product">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}


<div class="min-h-screen bg-gray-100 text-gray-800 antialiased px-4 py-6 flex flex-col justify-center sm:py-12">
    <div class="relative py-2 sm:max-w-xl mx-auto text-center">
      <span class="text-2xl font-light">Login to your account</span>
      <div class="relative mt-4 bg-white shadow-md sm:rounded-lg text-left">
        <div class="h-2 bg-indigo-400 rounded-t-md"></div>
        <div class="py-6 px-8">
            <form method="POST" action=""> 
                {% csrf_token %}
                <label class="block font-semibold">Username<label>
                <input type="text" name="username" placeholder="Username" class=" border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md">
                
                <label class="block mt-3 font-semibold">Password<label>
                <input type="password" name="password" placeholder="Password" class=" border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md">
            </form>
          <div class="flex justify-center">
            <button class="mt-5 bg-indigo-500 text-white py-2 px-20 rounded-lg hover:bg-indigo-600 " type="submit" value="Login">Login</button>
          </div>

          {% if messages %}
        <ul class="mt-2 mb-2">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
         {% endif %}

        Don't have an account yet? <a href="{% url 'main:register' %}" class="underline text-indigo-500 hover:text-indigo-600">Register Now</a>
        </div>
      </div>
    </div>
  </div>



{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
    td, tr, th, table {
        border: 2px solid black;
    }

    .plus-button {
    font-size: 16px; 
    border: none; 
    cursor: pointer; 
    text-align: center;
    margin-left: 5px;
    border-radius: 5px; 
    }

    .delete-button{
        color: white;
        cursor: pointer;
        background-color: #f44336;
        text-align: center;
        border: none;
        padding: 4px;
        border-radius: 5px;
    }

    .delete-button:hover {
        background-color: #d32f2f; /* Warna latar belakang saat dihover */
    }

    .minus-button{
    font-size: 16px; 
    border: none; 
    cursor: pointer; 
    text-align: center;
    margin-right: 5px;
    border-radius: 5px; 
    }
    
</style>

    <nav
    class="relative flex w-full flex-wrap items-center justify-between bg-indigo-500 py-2 shadow-lg lg:py-4">
    <div class="flex w-full flex-wrap items-center justify-between px-3">
        <h1 class="ml-2 text-xl text-white">Game Sthar</h1>
        <div class="flex px-5 items-center">
            <div>
                <p class="text-white mr-5">Welcome, {{ name }} from class {{class}}</p>
                <p class="text-white mr-5 text-sm">Sesi terakhir login: {{ last_login }}</p>
            </div>
            <button class="bg-green-500 text-white py-2 px-4 rounded-lg hover:bg-green-600" id="showPopUp">
                Add New Product by Ajax
            </button>
            <a href="{% url 'main:create_product' %}" class="mx-2">
                <button class="bg-green-500 text-white py-2 px-4 rounded-lg hover:bg-green-600">
                    Add New Product
                </button>
            </a>
            <a href="{% url 'main:logout' %}" >
                <button class="bg-red-500 text-white py-2 px-4 rounded-lg hover:bg-red-600">
                    Logout
                </button>
                </a>
        </div>
      
    </div>
    </nav>

    <br/>


    <div id="product_table" class="flex flex-wrap justify-center py-5 px-4 grow-0">

    </div>

    <div class="hidden z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true" id="modal">
        <!--
          Background backdrop, show/hide based on modal state.
      
          Entering: "ease-out duration-300"
            From: "opacity-0"
            To: "opacity-100"
          Leaving: "ease-in duration-200"
            From: "opacity-100"
            To: "opacity-0"
        -->
        <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>
      
        <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
          <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
            <!--
              Modal panel, show/hide based on modal state.
      
              Entering: "ease-out duration-300"
                From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                To: "opacity-100 translate-y-0 sm:scale-100"
              Leaving: "ease-in duration-200"
                From: "opacity-100 translate-y-0 sm:scale-100"
                To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            -->
            <div class="relative transform overflow-hidden rounded-lg bg-white text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-lg">
                <div class="relative py-2 sm:max-w-xl text-center">
                    <span class="text-2xl font-light">Add New Game</span>
                <div class="relative bg-white shadow-md sm:rounded-lg text-left">
                <div class="py-10 px-8">
                    <form id="form" onsubmit="return false;"> 
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class=" border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <input type="text" class=" border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md" id="description" name="description"></input>
                        </div>
                        <div class="mb-3">
                            <label for="category" class="col-form-label">Category:</label>
                            <input type="text" class=" border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md" id="category" name="category"></input>
                        </div>
                        <div class="mb-3">
                            <label for="platform" class="col-form-label">Platform:</label>
                            <input type="text" class=" border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md" id="platform" name="platform"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Amount:</label>
                            <input type="number" class=" border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md" id="amount" name="amount"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class=" border w-full h-5 px-3 py-5 mt-2 hover:outline-none focus:outline-none focus:ring-1 focus:ring-indigo-600 rounded-md" id="price" name="price"></input>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="bg-red-500 text-white py-2 px-4 rounded-lg hover:bg-red-600" id="close_button"">Close</button>
                            <button type="button" class="bg-green-500 text-white py-2 px-4 rounded-lg hover:bg-green-600" id="button_add">Add Product</button>
                        </div>
                    </form>
                </div>
            </div>
          </div>
        </div>
      </div>






    <script>

        async function getProducts() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json());
        }
    
        async function refreshProducts() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getProducts()
        let htmlString = ''
        products.forEach((item) => {
            htmlString += ` <div class=" px-2 flex flex-col bg-white rounded-lg shadow-md w-80 m-6 overflow-hidden w-80">
        
        <div class=" flex justify-between px-2 pt-4">
            <h1 class="px-2 text-xl">${ item.fields.name }</h1> 
            <button class="delete-button" onClick=deleteProduct(${item.pk})>Delete</button>
        </div>
        <div class="text-sm pl-2 pt-3">
            <p>Amount :</p>
            <div class=flex>
            <button onClick=decreaseProduct(${item.pk}) class ="minus-button">-</button>
            <p>${item.fields.amount}</p>
            <button onClick=increaseProduct(${item.pk})  class="plus-button">+</button>
            </div>
        </div>
        <p class="pt-3">${ item.fields.description } </p>
       
        <div class="pt-4 pb-6">
            <p class="text-sm"><b>Category: </b>${ item.fields.category } </p>
            <p class="text-sm"><b>Price: </b>${ item.fields.price } </p>
        </div>
    
    </div>` 
        })
        
        document.getElementById("product_table").innerHTML = htmlString
    }

    refreshProducts()

    async function deleteProduct(id){
        await fetch (`delete-product-ajax/${id}`,{
            method: "DELETE"
        }).then(refreshProducts);
    }
    
    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()

        return false
    }

    $("#button_add").click(function () {
    addProduct(); 
    $("#modal").css("display", "none"); 
    });

    $("#close_button").click(function() {
        $("#modal").css("display", "none");
    })

    async function increaseProduct(id){
        let form = new FormData();
        form.append("id", id);
        await fetch("increase_amount/", {
            method: "POST",
            body: form,
        }).then(refreshProducts);
        }

    async function decreaseProduct(id){
        let form = new FormData();
        form.append("id", id);
        await fetch("decrease_amount/", {
            method: "POST",
            body: form,
        }).then(refreshProducts);
        }

    $(document).ready(function() {
            $("#showPopUp").click(function() {
                $("#modal").css("display", "block");
                document.getElementById("form").reset();
            });
        });
    
    </script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}

<div class="login">

<div class="min-h-screen bg-gray-100 text-gray-800 antialiased px-4 py-6 flex flex-col justify-center sm:py-12">
    <div class="relative py-2 sm:max-w-xl mx-auto text-center">
      <span class="text-2xl font-light">Register your account</span>
      <div class="relative mt-4 bg-white shadow-md sm:rounded-lg text-left">
        <div class="h-2 bg-indigo-400 rounded-t-md"></div>
        <div class="py-6 px-8">
        <form method="POST">
            {% csrf_token %}
                {{ form.as_p }}
            <div class="flex justify-center">
                <button class="mt-5 bg-indigo-500 text-white py-2 px-20 rounded-lg hover:bg-indigo-600 " type="submit" name="submit">Register</button> <!-- register form -->
            </div>
        </form>


    <!-- kalau tidak valid -->
    {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

   

</div>

{% endblock content %}